### ISSUE TITLE
Our Guild transferred servers.

### ISSUE THREAD

**Issue by UmbraChimera** [TheGeneticsGuy/Guild-Roster-Manager#49] opened 2024-08-18 23:41 UTC
Our Guild transferred servers to the Easter Eggs no longer run.

**Comment by UmbraChimera** [comment] 2024-08-18 23:42
`-- { GuildName , What to Say }
GRM_G.listOfGuilds = {
    ["Mysterious Intent-Tichondrius"] = "RogFactor",
    ["Is a Subatomic Particle-Zul'jin"] = "SAP Times"

}

GRM_G.listOfPlayers = {
    ["Tauros-EmeraldDream"] = "|cffff0000R" .. "|cffff6a00o" .. "|cfffff700g" .. "|cff44ff00F" .. "|cff0000ffa" .. "|cffa200ffc" .. "|cffff00f2t" .. "|cffff0000o" .. "|cffff6a00r", -- Gonna make this colorful for fun.

}`

**Comment by TheGeneticsGuy** [comment] 2024-08-25 09:18
oh haha - I can update it lol - I just realized I missed this message now... I'll add your changes in my next build. Sorry, I should have looked or I would have wrapped it in my 1.9912 build I just deployed 20 minutes ago :(

Thanks for the heads up though!

**Comment by UmbraChimera** [comment] 2024-08-31 02:22
For some reason this isn't working. Not sure why.

**Comment by TheGeneticsGuy** [comment] 2024-08-31 02:27
Is the data saying "unknown" by chance? If so, there is some weird bug that popped up out of nowhere and blocking people from seeing their join dates and thus no mouseover.

**Comment by UmbraChimera** [comment] 2024-08-31 02:56
![image](https://github.com/user-attachments/assets/d1d463df-a7f1-4b93-8c7b-b65082232f74)
Yep!

**Comment by TheGeneticsGuy** [comment] 2024-08-31 02:58
I am just finishing something real fast, but then I will be tackling the "unknown" ui bug and will hopefully push an update tonight. I am not sure how complicated the issue is yet, but it's probably minor as I can see the underlying data is still there in the audit, so it's just showing unknown for some reason. I recently rewrote this so that's probably something I typo'd is my guess. I'll have something soon.

**Comment by TheGeneticsGuy** [comment] 2024-08-31 02:59
I am guessing you are Umbra from discord, right? :D

**Comment by TheGeneticsGuy** [comment] 2024-08-31 10:49
This is fixed in current build. THANK YOU!

**Closed as completed by TheGeneticsGuy** 2024-08-31 10:49 UTC
